export const data = [
    {
      "name": "Food Xpress",
      "url": "/images/foodie.png",
      "link": "https://zionnairelanding.netlify.app/",
      "description": "A food ordering app that provides convinience for users anywhere",
      "date": "2023-07-18",
      "type": "image/png",
    },
    {
      "name": "WeSkillYou",
      "url": "/images/weskillyou.png",
      "link": "https://adetutu-weskillyou.netlify.app/",
      "description": "An app built with Nextjx. Designed to provide entrepreneurial skill acquisition for users",
      "date": "2023-07-09",
      "type": "image/png",
    },
    {
      "name": "Food Dairy",
      "url": "/images/Foodary.png",
      "link": "https://zionnaire-foodary.web.app/",
      "description": "An App for food recipes",
      "date": "2020-06-09",
      "type": "image/png",
    },
    {
      "name": "Landing Page",
      "url": "/images/landingpage.png",
      "link": "https://zionnairelanding.netlify.app/",
      "description": "A responsive landing page",
      "date": "2020-01-04",
      "type": "image/png",
    },
    {
      "name": "Lagos Ride",
      "url": "/images/LagosRide.png",
      "link": "https://lagosrides.netlify.app/",
      "description": "A beautiful ride hailing app for Lagosians",
      "date": "2020-01-05",
      "type": "image/png",
    },
    {
      "name": "Calculator App",
      "url": "/images/calculator.png",
      "link": "https://zionnaire-calculator-app.netlify.app/",
      "description": "A simple calculator that works perfectly",
      "date": "2020-01-06",
      "type": "image/png",
    },
  
    {
      "name": "Planner App",
      "url": "/images/planner-app.png",
      "link": "https://zionnaire1-planner-app.netlify.app/",
      "description": "Waterfall in Nigeria",
      "date": "2020-01-08",
      "type": "image/jpg",
    },
    {
      "name": "Waterfront",
      "url": "images/Waterfront.jpeg",
      "link": "https://zionnairelanding.netlify.app/",
      "description": "A beautiful Water pictorial",
      "date": "2020-01-09",
      "type": "image/jpg",
    }
  ]